### ISSUE TITLE
vector cluster: get_seq does not exist

### ISSUE THREAD

**Issue by fabiofumarola** [chrisPiemonte/url2vec#1]
```
]:

get_sequences
# because of generator
vocab_sequences = get_seq(rwwl_seq_path, 1)
train_sequences = get_seq(rwwl_seq_path, 1)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-6-cfe3d39eb95e> in <module>()
      1 # because of generator
----> 2 vocab_sequences = get_seq(rwwl_seq_path, 1)
      3 train_sequences = get_seq(rwwl_seq_path, 1)

NameError: name 'get_seq' is not defined

```

**Comment by chrisPiemonte** [comment]
correggo e pusho

**Comment by fabiofumarola** [comment]
mitico :+1:

**Comment by chrisPiemonte** [comment]
è cambiata la generazione del dataset e ho dovuto cambiare alcune funzioni. Entro domani metto tutto in ordine. Giuro

**Comment by fabiofumarola** [comment]
Non ti preoccupare, sistema con calma. Volevo solo collaborare nel progetto
:)

On Wednesday, January 27, 2016, Chris notifications@github.com wrote:

> è cambiata la generazione del dataset e ho dovuto cambiare alcune
> funzioni. Entro domani metto tutto in ordine. Giuro
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chrisPiemonte/url2vec/issues/1#issuecomment-175824324
> .

## 

Sent from Gmail Mobile

**Comment by fabiofumarola** [comment]
penso sia stato chiuso in qualche issue
